include:
  - remote: https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/main/.gitlab-ci/docker-ros.yml

variables:
  BASE_IMAGE: rwthika/ros2:jazzy
  RMW_IMPLEMENTATION: rmw_zenoh_cpp
  COMMAND: ros2 launch ackermann_trajectory_control ackermann_trajectory_control_node.launch.py
  PLATFORM: amd64
  TARGET: dev,run
  ENABLE_INDUSTRIAL_CI: 'true'
  ENABLE_RECURSIVE_VCS_IMPORT: 'false'