trajectory_control_node:
  ros__parameters:
    # General controller parameters
    vehicle_frame_id: "base_link"
    fixed_over_time_frame_id: "map"
    control_frequency: 100.0 # [Hz]
    vehicle_state_timeout: 0.2 # [s]
    lateral_lookahed_time: 0.1 # [s]
    longitudinal_lookahed_time: 0.1 # [s]

    # Inverse single track parameters
    wheelbase: 2.711 # [m]
    selfsteergradient: 0.002917853041365

    # Control value constraints
    max_longitudinal_acceleration: 3.5 # [m/s^2]
    min_longitudinal_acceleration: -5.0 # [m/s^2]
    max_longitudinal_jerk: 5.0 # [m/s^3]
    max_steering_angle: 28.0 # [deg]
    max_steering_angle_rate: 56.0 # [deg/s]

    # Gain scheduling Look-Up-Tables
    velocity_lookup: # [m/s]
      - -2.78
      - -0.2
      -  0.0
      -  0.2
      -  2.78
      - 11.11
      - 16.67
      - 22.22
      - 27.78
      - 33.33
      - 38.89  
    feed_forward_acceleration_gain:
      - 0.0 # value for -2.78 m/s
      - 0.0 # value for -0.2 m/s
      - 1.0 # value for  0.0 m/s
      - 1.0 # value for  0.2 m/s
      - 1.0 # value for  2.78 m/s
      - 1.0 # value for 11.11 m/s
      - 1.0 # value for 16.67 m/s
      - 1.0 # value for 22.22 m/s
      - 1.0 # value for 27.78 m/s
      - 1.0 # value for 33.33 m/s
      - 1.0 # value for 38.89 m/s  
    feed_forward_steering_angle_gain:
      - 0.0 # value for -2.78 m/s
      - 0.0 # value for -0.2 m/s
      - 1.0 # value for  0.0 m/s
      - 1.0 # value for  0.2 m/s
      - 1.0 # value for  2.78 m/s
      - 1.0 # value for 11.11 m/s
      - 1.0 # value for 16.67 m/s
      - 1.0 # value for 22.22 m/s
      - 1.0 # value for 27.78 m/s
      - 1.0 # value for 33.33 m/s
      - 1.0 # value for 38.89 m/s
    # Velocity controller parameters
    dv_p:
      - 1.0 # value for -2.78 m/s
      - 1.0 # value for -0.2 m/s
      - 1.0 # value for  0.0 m/s
      - 1.0 # value for  0.2 m/s
      - 1.0 # value for  2.78 m/s
      - 1.0 # value for 11.11 m/s
      - 1.0 # value for 16.67 m/s
      - 1.0 # value for 22.22 m/s
      - 1.0 # value for 27.78 m/s
      - 1.0 # value for 33.33 m/s
      - 1.0 # value for 38.89 m/s
    dv_i:
      - 0.0 # value for -2.78 m/s
      - 0.0 # value for -0.2 m/s
      - 0.0 # value for  0.0 m/s
      - 0.0 # value for  0.2 m/s
      - 0.0 # value for  2.78 m/s
      - 0.0 # value for 11.11 m/s
      - 0.0 # value for 16.67 m/s
      - 0.0 # value for 22.22 m/s
      - 0.0 # value for 27.78 m/s
      - 0.0 # value for 33.33 m/s
      - 0.0 # value for 38.89 m/s
    dv_d:
      - 0.0 # value for -2.78 m/s
      - 0.0 # value for -0.2 m/s
      - 0.0 # value for  0.0 m/s
      - 0.0 # value for  0.2 m/s
      - 0.0 # value for  2.78 m/s
      - 0.0 # value for 11.11 m/s
      - 0.0 # value for 16.67 m/s
      - 0.0 # value for 22.22 m/s
      - 0.0 # value for 27.78 m/s
      - 0.0 # value for 33.33 m/s
      - 0.0 # value for 38.89 m/s
    # Lateral deviation controller parameters
    dy_p:
      - 0.1   # value for -2.78 m/s
      - 0.1   # value for -0.2 m/s
      - 0.1   # value for  0.0 m/s
      - 0.1   # value for  0.2 m/s
      - 0.1   # value for  2.78 m/s
      - 0.05  # value for 11.11 m/s
      - 0.03  # value for 16.67 m/s
      - 0.025 # value for 22.22 m/s
      - 0.025 # value for 27.78 m/s
      - 0.025 # value for 33.33 m/s
      - 0.02  # value for 38.89 m/s
    dy_i:
      - 0.004  # value for -2.78 m/s
      - 0.002  # value for -0.2 m/s
      - 0.0    # value for  0.0 m/s
      - 0.002  # value for  0.2 m/s
      - 0.002  # value for  2.78 m/s
      - 0.004  # value for 11.11 m/s
      - 0.001  # value for 16.67 m/s
      - 0.0007 # value for 22.22 m/s
      - 0.0    # value for 27.78 m/s
      - 0.0    # value for 33.33 m/s
      - 0.0    # value for 38.89 m/s
    dy_d:
      - 0.04  # value for -2.78 m/s
      - 0.02  # value for -0.2 m/s
      - 0.0   # value for  0.0 m/s
      - 0.02  # value for  0.2 m/s
      - 0.04  # value for  2.78 m/s
      - 0.02  # value for 11.11 m/s
      - 0.02  # value for 16.67 m/s
      - 0.02  # value for 22.22 m/s
      - 0.015 # value for 27.78 m/s
      - 0.015 # value for 33.33 m/s
      - 0.015 # value for 38.89 m/s
    # heading deviation controller parameters
    dpsi_p:
      - 1.0 # value for -2.78 m/s
      - 1.0 # value for -0.2 m/s
      - 1.0 # value for  0.0 m/s
      - 1.0 # value for  0.2 m/s
      - 1.0 # value for  2.78 m/s
      - 1.0 # value for 11.11 m/s
      - 1.0 # value for 16.67 m/s
      - 1.0 # value for 22.22 m/s
      - 1.0 # value for 27.78 m/s
      - 1.0 # value for 33.33 m/s
      - 1.0 # value for 38.89 m/s
    dpsi_i:
      - 1.2  # value for -2.78 m/s
      - 1.2  # value for -0.2 m/s
      - 1.2  # value for  0.0 m/s
      - 1.2  # value for  0.2 m/s
      - 1.2  # value for  2.78 m/s
      - 0.6  # value for 11.11 m/s
      - 0.4  # value for 16.67 m/s
      - 0.14 # value for 22.22 m/s
      - 0.13 # value for 27.78 m/s
      - 0.13 # value for 33.33 m/s
      - 0.13 # value for 38.89 m/s
    dpsi_d:
      - 0.0 # value for -2.78 m/s
      - 0.0 # value for -0.2 m/s
      - 0.0 # value for  0.0 m/s
      - 0.0 # value for  0.2 m/s
      - 0.0 # value for  2.78 m/s
      - 0.0 # value for 11.11 m/s
      - 0.0 # value for 16.67 m/s
      - 0.0 # value for 22.22 m/s
      - 0.0 # value for 27.78 m/s
      - 0.0 # value for 33.33 m/s
      - 0.0 # value for 38.89 m/s

